### PR TITLE
Keyboard shortcuts

### PR DESCRIPTION
**Pull request by Hollish**
Added skip and store toggling. 'z' will toggle skip, 'x' will toggle
storing. Holding shift will also toggle skip until released.

### CODE REVIEW

**Comment by Hollish** [comment]
I don't know if the holding shift thing should be added just yet, it would work better if enabling skip didn't force you to the next image. The intent was to be able to hold shift to go back to a post if you skipped it but changed your mind. The problem is that once you're on the post, letting go moves you to the next new post.

**Comment by asarode** [comment]
Nice, this is shaping up to look good. I haven't had a chance to test it yet though. Can you please set the toggling hotkeys to alt+z and alt+x (or some other key+z/key+x combo). Otherwise it could be annoying when typing a comment.

**Comment by Hollish** [comment]
Fair point. Picking hotkeys is not my strong suit. I'll do alt.

**Comment by asarode** [comment]
I couldn't get it to work when I tried it. I think it's because the keyup event doesn't have two keys in one event firing. Check this out to help figure out how to check for two keys at once: http://stackoverflow.com/a/12444641

**Comment by Hollish** [comment]
The event structure sends the mod keys status in keyup and key down events.
When I tried it, it wouldn't work with keypress. Can you run your debugger
and enable the keyup breakpoint? How quickly are you trying the combo?

**Comment by asarode** [comment]
Oh yeah, it's working fine! Checking on key up feels pretty weird. It's nicer to be able to hold alt and then kit z or x to do enable the hot key. Are you fine with that change in behavior? Changing the event from keyup to keydown should get what we want. I'll merge when you make that change.

**Comment by asarode** [comment]
Btw, I setup a Gitter for this repo. It's just a chatroom where people can talk about development for seen-it. Here's the link (you can also click the badge on top of the readme): https://gitter.im/asarode/seen-it

**Pull request merged**
