### PR TITLE
prevent skip on previous action

### PR DESCRIPTION
**Pull request by Platane**
Hello,

I wanted to add behavior such as not skipping when I hit the previous key.

I made a try: the next action ( shortcuts and buttons ) are catched and a message is sent to the background script, which then sets a `doNotSkipNext` flag.

Problem is, the message is received after the url change event.

I will try to figure out another way to achieve that.

I personnaly prefer this behavior, do you think it could be useful to have it as option ?

### CODE REVIEW

**Comment by asarode** [comment]
You can now toggle the skipping with alt+z. There's a plan to toggle the skipping when you hold shift+left or shift+right an then toggle it again once you let go of shift. I think the shift behavior is a bit more flexible than just not skipping when you press the back key. Do you think it would still be necessary that the back button not trigger a skip if this shift functionality is added?

**Comment by Platane** [comment]
The shift mecanism will be fine sure !

How do you plans to detetect the shift key ?

I was thinking of waiting for the message before executing the code to parse url. But I checked and the message arrives ~200ms after, which is a lot to wait I think.

**Comment by asarode** [comment]
I think you'd need to add a quickDisableIsActive flag variable that would be stored in local storage. When the user holds shift+direction down, check if the flag is false. If it is false, set the flag to true and disable skipping in local storage.

Then when you land on the next page, the skipping is disabled (so the image doesn't skip) and the quickDisableIsActive flag is true. Now listen for when the user lifts the key up and the shift key isn't active in the onkeyup event. When this happens, set the quickDisableIsActive flag to false and enable skipping again.

This is the implementation that I can think of, but there may be better ways.

**Comment by Platane** [comment]
ok, smart

I will implement this this week end

**Comment by asarode** [comment]
I just merged in #19 so when you enable skipping on a page, you won't automatically get thrown onto the next unseen image. This will probably make this quick toggling feature much nicer :)

**Comment by Platane** [comment]
Hello again, I did the modifications.

I add methods to utils/storage. It may be confusing since the methods here  work with the localStorage of the extension, whereas the ones I added work with the page localStorage.

I add a message passed from the extension to the content script which notifies that the history checking have been done and that the flag can be reset.

**Comment by asarode** [comment]
Thanks for the help! It works like a charm! I added a way to optionally set the default value returned by `safeGetBool` The first time you try to get the `doNotSkipNext` flag and it's `null`, the default value should be `false` instead of `true` like is normally is in `safeGetBool`.

**Comment by Platane** [comment]
Cool thanks !

**Pull request merged**
